pool:
  vmImage: ubuntu-latest
trigger: none

parameters:
- name: runStageB
  displayName: Run Stage B
  type: boolean
  default: true
- name: runStageC
  displayName: Run Stage C
  type: boolean
  default: true
- name: runStageD
  displayName: Run Stage D
  type: boolean
  default: true

stages:
- stage: A
  displayName: Stage A
  jobs:
  - job: JobA
    steps:
    - bash: echo "Job A"

- ${{ if eq(parameters.runStageB, true) }}:
  - stage: B
    displayName: Stage B
    dependsOn:
    - A
    jobs:
    - job: JobB
      steps:
      - bash: echo "Job B"

- ${{ if eq(parameters.runStageC, true) }}:
  - stage: C
    displayName: Stage C
    dependsOn:
    - B
    jobs:
    - job: JobC
      steps:
      - bash: echo "Job C"

- ${{ if eq(parameters.runStageD, true) }}:
  - stage: D
    displayName: Stage D
    dependsOn:
    - C
    jobs:
    - job: JobD
      steps:
      - bash: echo "Job D"