pool:
  vmImage: ubuntu-latest
trigger: none

parameters:
- name: runStageB
  displayName: Run Stage B
  type: boolean
  default: true
- name: runStageC
  displayName: Run Stage C
  type: boolean
  default: true
- name: runStageD
  displayName: Run Stage D
  type: boolean
  default: true

variables:
- name: stageCDependsOn
  value: B2
${{ if eq(parameters.runStageB, false) }}: 
  - name: stageCDependsOn
    value: A

stages:
- stage: A
  displayName: Stage A
  jobs:
  - job: JobA
    steps:
    - bash: echo "Job A"

- ${{ if eq(parameters.runStageB, true) }}:
  - stage: B1
    displayName: Stage B1
    dependsOn:
    - A
    jobs:
    - job: JobB1
      steps:
      - bash: echo "Job B1"

  - stage: B2
    displayName: Stage B2
    dependsOn:
    - B1
    jobs:
    - job: JobB2
      steps:
      - bash: echo "Job B2"

- ${{ if eq(parameters.runStageC, true) }}:
  - stage: C1
    displayName: Stage C1
    dependsOn:
    - $()
    jobs:
    - job: JobC1
      steps:
      - bash: echo "Job C1"

  - stage: C2
    displayName: Stage C2
    dependsOn:
    - C1
    jobs:
    - job: JobC2
      steps:
      - bash: echo "Job C2"

- ${{ if eq(parameters.runStageD, true) }}:
  - stage: D
    displayName: Stage D
    dependsOn:
    - C2
    jobs:
    - job: JobD
      steps:
      - bash: echo "Job D"