pool:
  vmImage: ubuntu-latest

parameters:
- name: runStageA
  displayName: Run Stage A
  type: boolean
  default: true
- name: runStageB
  displayName: Run Stage B
  type: boolean
  default: true
- name: runStageC
  displayName: Run Stage C
  type: boolean
  default: true

stages:
- stage: A
  jobs:
  - job: JobA
    steps:
    - bash: echo "Job A"

- stage: B
  jobs:
  - job: JobB
    steps:
    - bash: echo "Job B"

- stage: C
  jobs:
  - job: JobC
    steps:
    - bash: echo "Job C"