pool:
  vmImage: ubuntu-latest

parameters:
  runStageA: true
  runStageB: true
  runStageC: true

stages:
- stage: A
  jobs:
  - job: JobA
    steps:
    - bash: echo "Job A"

- stage: B
  jobs:
  - job: JobB
    steps:
    - bash: echo "Job B"

- stage: C
  jobs:
  - job: JobC
    steps:
    - bash: echo "Job C"